# Preview commands only. Running this file would launch OpenClaw agent work.
# Generated from C:\FOC\Workspace\incoming\LPOC.openclaw-cleanlimit-20260617-051710.json
# Thinking is taken from OpenClaw model defaults in C:\FOC\.openclaw\openclaw.json; no --thinking override is passed.

& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq15208' --model 'nv-minimax-m3/minimaxai/minimax-m3' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 15208. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ15208.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq20013' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 20013. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ20013.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq20214' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 20214. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ20214.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq20681' --model 'nv-minimax-m3/minimaxai/minimax-m3' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 20681. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ20681.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq17071' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 17071. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ17071.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq21592' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 21592. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ21592.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq21005' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 21005. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ21005.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq18948' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 18948. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ18948.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq17570' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 17570. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ17570.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq20618' --model 'openrouter/poolside/laguna-m.1:free' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 20618. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ20618.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq19141' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 19141. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ19141.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq19222' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 19222. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ19222.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq18799' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 18799. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ18799.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq19493' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 19493. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ19493.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq20329' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 20329. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ20329.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq19614' --model 'openrouter/poolside/laguna-m.1:free' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 19614. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ19614.md.'
