# Preview commands only. Running this file would launch OpenClaw agent work.
# Review first, or use Start-OpenClawLPOCBatch.ps1 for dry-run and launch controls.
# Thinking is taken from OpenClaw model defaults in C:\FOC\.openclaw\openclaw.json; no --thinking override is passed.

& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14423' --model 'xai/grok-build-0.1' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14423. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14423.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14990' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14990. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14990.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq15050' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 15050. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ15050.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14894' --model 'minimax/MiniMax-M3' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14894. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14894.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14809' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14809. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14809.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14881' --model 'minimax/MiniMax-M3' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14881. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14881.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14861' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14861. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14861.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14980' --model 'openai/gpt-5.5' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14980. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14980.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq15059' --model 'xai/grok-build-0.1' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 15059. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ15059.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq14487' --model 'xai/grok-build-0.1' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 14487. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ14487.md.'
& 'C:\FOC\bin\openclaw.ps1' --no-color agent --agent 'main' --session-key 'cq15074' --model 'openrouter/owl-alpha' --verbose 'on' --timeout '28800' --json --message 'Please do this BarMatrix Multiple Choice Bar Exam Question 15074. Complete any research needed, do not stop at planning, verify your work, and save the entire response to C:\FOC\Workspace\Finished\CQ15074.md.'
