-- AUTO-GENERATED by scripts/content_reset_foc_projections.mjs.
-- Clears projection rows/fields only for inactive FOC draft questions.
SET NAMES utf8mb4;
START TRANSACTION;

DELETE qt FROM question_tags qt
JOIN questions q ON q.question_id = qt.question_id
WHERE q.status = 'draft' AND q.source_type = 'c3_transformed';

DELETE ca FROM c3_annotations ca
JOIN questions q ON q.question_id = ca.question_id
WHERE q.status = 'draft' AND q.source_type = 'c3_transformed';

UPDATE answer_choices ac
JOIN questions q ON q.question_id = ac.question_id
SET ac.c3_filter_broken = NULL,
    ac.c3_mold_code = NULL,
    ac.c3_architecture = NULL,
    ac.forensic_tags = '[]',
    ac.misconception_tags = '[]'
WHERE q.status = 'draft' AND q.source_type = 'c3_transformed';

UPDATE questions
SET tension_point = NULL
WHERE status = 'draft' AND source_type = 'c3_transformed';

COMMIT;
